name: side_swap_ffi

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  ffigen:

ffigen:
  name: NativeLibrary
  output: '../lib/side_swap_client_ffi.dart'
  description: 'SideSwap FFI'
  headers:
    entry-points:
      - 'gen/side_swap_client_ffi.h'
  functions:
    include:
      - 'sideswap_.*'
