[package]
name = "gdk-common"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "William Casarin <jb55@jb55.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
chrono = "0.4.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
libc = "0.2"
hex = "0.4.0"
rand = "0.7.3"
bitcoin = { version = "0.25", features = ["use-serde"] }
elements = { version = "0.13", features = ["serde-feature"] }

